---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.deployment.image.tag }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/managed-by: helm
    {{- with .Values.serviceaccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.deployment.podLabels }}
  annotations: {{- toYaml .Values.serviceaccount.annotations | nindent 4 }}
  {{- end }}
---